[0m11:41:23.015347 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79c98826a270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79c9891e65d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79c9891e7a40>]}


============================== 11:41:23.035354 | fc970c8f-1ead-48b8-8b2e-395ca57bcd7d ==============================
[0m11:41:23.035354 [info ] [MainThread]: Running with dbt=1.10.4
[0m11:41:23.037669 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/apple_shay/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt init etl_dbt', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:41:23.540474 [debug] [MainThread]: Starter project path: /mnt/b/de/ETL1/etl_pipeline_project/venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m11:41:24.357788 [info ] [MainThread]: 
Your new dbt project "etl_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:41:24.360337 [info ] [MainThread]: Setting up your profile.
[0m11:42:30.808457 [info ] [MainThread]: Profile etl_dbt written to /home/apple_shay/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:42:30.820324 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 67.92808, "process_in_blocks": "15880", "process_kernel_time": 1.589626, "process_mem_max_rss": "102016", "process_out_blocks": "8", "process_user_time": 2.335949}
[0m11:42:30.823859 [debug] [MainThread]: Command `dbt init` succeeded at 11:42:30.823608 after 67.93 seconds
[0m11:42:30.827152 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79c988914e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79c9888ef7a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x79c98806ce30>]}
[0m11:42:30.830067 [debug] [MainThread]: Flushing usage events
[0m11:42:31.424349 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:17:31.001558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7947e5105d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7947e69a47a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7947e449ff80>]}


============================== 12:17:31.031428 | 4f68c025-91f5-40fa-bd9f-d537f9b425eb ==============================
[0m12:17:31.031428 [info ] [MainThread]: Running with dbt=1.10.4
[0m12:17:31.033974 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/apple_shay/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:17:31.036936 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /mnt/b/de/ETL1/etl_pipeline_project/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:17:31.045048 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.1274397, "process_in_blocks": "26064", "process_kernel_time": 1.530744, "process_mem_max_rss": "97632", "process_out_blocks": "0", "process_user_time": 2.060108}
[0m12:17:31.046875 [debug] [MainThread]: Command `dbt run` failed at 12:17:31.046440 after 0.13 seconds
[0m12:17:31.049252 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7947e4be6ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7947e423d1f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7947e46c5280>]}
[0m12:17:31.051942 [debug] [MainThread]: Flushing usage events
[0m12:17:31.537408 [debug] [MainThread]: An error was encountered while trying to flush usage events
